# Generated by Django 4.0.1 on 2022-01-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('1', 'LEI'), ('2', '€')], default='LEI', max_length=5),
        ),
    ]
