# Generated by Django 4.0.1 on 2022-01-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('LEI', 'LEI'), ('€', '€')], default='1', max_length=5),
        ),
    ]
