# Generated by Django 4.0.1 on 2022-01-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_product_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
