# Generated by Django 4.0.1 on 2022-01-11 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_first_name_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_adder', to='app.customer'),
        ),
    ]
