# Generated by Django 4.0.1 on 2022-01-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
    ]
